pipeline {
    agent none
    stages {
        stage('Back-end') {
            agent {
                docker {
                    image 'maven:3.9.6-eclipse-temurin-17-alpine'  // latest Maven + JDK 17
                }
            }
            steps {
                timeout(time: 5, unit: 'MINUTES') {
                    sh 'mvn --version'
                    sh 'mvn clean install'
                }
            }
        }
        stage('Front-end') {
            agent {
                docker {
                    image 'node:22-alpine'  // latest Node.js LTS
                }
            }
            steps {
                timeout(time: 5, unit: 'MINUTES') {
                    sh 'node --version'
                    sh 'npm install'
                    sh 'npm run build'
                }
            }
        }
    }
}
